config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'welcome/index'
  
  resources :articles do
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
    length: { minimum: 4 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  Password_Requirement = /\A
  (?=.{8,}) #Atleast 8 characters long
  (?=.*\d) #Atleast contain 1 number
  (?=.*[a-z]) #Contain atleast one lowercase letter
  (?=.*[A-Z]) #Contain atleast one uppercase letter
  (?=.*[[:^alnum:]]) #Contain atleast one symbol
  /x

  enum role: { admin: 0, user: 1 }

  has_many :articles, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :password, format: Password_Requirement


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
  def user_not_authorized
    flash[:notice] = 'You are not authorized to perform this action.'
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    begin
      @article = Article.all
    rescue ActiveRecord::RecordNotFound
      error!({ status: :error, message: :not_found }, 404)
    end
  end

  def show
    begin
      @article = Article.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      error!({ status: :error, message: :not_found }, 404)
    end
  end

  def new
    @article = Article.new
  end

  def edit
    begin
      @article = Article.find(params[:id])
      authorize @article
    rescue ActiveRecord::RecordNotFound
      error!({ status: :error, message: :not_found }, 404)
    end
  end

  def create
    @user = User.find(current_user.id)
    @article = @user.articles.create(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    authorize @article
    if @article.update(article_params)
      flash[:notice] = "Successfully Updated."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize @article
    if @article.destroy
      flash[:notice] = "Successfully Deleted."
      redirect_to articles_path
    else
      flash.now[:notice] = "There was an error deleting the article."
      redirect_to articles_path
    end
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    if @comment.destroy
      flash[:notice] = "Successfully Deleted."
      redirect_to article_path(@article)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Email or password Is Invalid"
      render "_login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    begin
      @users = User.all
      authorize @users
    rescue ActiveRecord::RecordNotFound
      error!({ status: :error, message: :not_found }, 404)
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User Successfully Created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update(user_params)
      flash[:notice] = "Successfully Updated."
      redirect_to user_path
    else
      render :edit
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User Successfully Destroyed.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    begin
      @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      error!({ status: :error, message: :not_found }, 404)
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block', id: "alert")
  end

  def form_group_for(form, field, opts={}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<% if current_user %>
  <%= form_with(model: @article, local: true) do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <form>
      <div class="form-group input-box">
        <h1>Edit Article</h1>
        <p>
          <%= form.text_field :title, :class => "form-control", :placeholder => "Title" %>
        </p>
        <p>
          <%= form.text_area :text, :class => "form-control", :placeholder => "Description", :rows => "10" %>
        </p>
        <p>
          <%= form.submit :Submit, :class => "btn btn-primary col-4" %>
          <%= link_to 'Back', articles_path, :class => "btn btn-dark col-4" %>
        </p>
      </div>
    <% end %>
  </form>
<% else %>
  <%= render "sessions/login" %>
<% end %>

app/views/articles/index.html.erb
<% if current_user %>
  <%= render "sessions/destroy" %>
  <div class="mt-5">
    <h6 id="notice"><%= notice %></h6>
    <%= link_to 'Create article', new_article_path, :class => "btn btn-outline-primary btn-lg" %>
  </div>
  <div class="container border border-light bg-color">
    <h1 class="mb-5">Blogs</h1>
    <% @article.each_with_index do |article_element, index| %>
      <div>
        <div class="row ">
          <div class="col-md-2">
            <p><%= index+1 %></p>
          </div>
          <div class="col-md-2">
            <p><%= article_element.title %></p>
          </div>
          <div class="col-md-4">
            <p><%= article_element.text.truncate(100) %></p>
          </div>
          <div class="col-md-4">
            <%= link_to ('<i class="btn-mg fas fa-eye"></i>').html_safe, article_path(article_element) %>
            <%= link_to ('<i class=" btn-mg fas fa-user-edit"></i>').html_safe, edit_article_path(article_element) %>
            <%= link_to ('<i class="btn-mg far fa-trash-alt"></i>').html_safe, article_path(article_element),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
        <hr class="my-4 mx-4">
      </div>
    <% end %>
  </div>
<% else %>
  <%= render "sessions/login" %>
<% end %>

app/views/articles/new.html.erb
<% if current_user %>
  <%= form_with scope: :article, url: articles_path, local: true do |form| %>
    <% if @article.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@article.errors.count, "error") %> prohibited
          this article from being saved:
        </h2>
        <ul>
          <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <form>
      <div class="form-group input-box">
        <p>
          <%= form.text_field :title, :class => "form-control", :placeholder => "Title" %>
        </p>
        <p>
          <%= form.text_area :text, :class => "form-control", :placeholder => "Description", :rows => "10" %>
        </p>
        <p>
          <%= form.submit :Submit, :class => "btn btn-primary col-4" %>
          <%= link_to 'Back', articles_path, :class => "btn btn-dark col-4" %>
        </p>
      </div>
    <% end %>
  </form>
<% else %>
  <%= render "sessions/login" %>
<% end %>

app/views/articles/show.html.erb
<% if current_user %>
  <%= render "sessions/destroy" %>
  <div class="container bg-color">
    <div class="row">
      <div class="col">
        <h2><%= @article.title %></h2>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <p class="para-font"><%= @article.text %></p>
      </div>
    </div>
    <div>
      <h6>- <%= User.find(@article.user_id).first_name + " " + User.find(@article.user_id).last_name %></h6>
    </div>
  </div>
  <div class="container bg-color">
    <h2 >Comments</h2>
    <%= render @article.comments %>
  </div>
  <div class="input-box">
    <h2>Add a comment: </h2>
    <%= render 'comments/form' %>
    <%= link_to 'Back', articles_path, :class => "btn btn-outline-dark col-9" %>
  </div>
<% else %>
  <%= render "sessions/login" %>
<% end %>

app/views/comments/_comment.html.erb
<div class="comments">
  <div class="row">
    <div class="col">
      <h5><%= comment.commenter %></h5>
    </div>
  </div>
  <div class="row">
    <div class="col mb-2">
      <%= comment.body %>
    </div>
  </div>
  <% if (@article.user_id == current_user.id) || (current_user.role == "admin") %>
    <div class="row">
      <div class="col">
        <%= link_to 'Delete', [comment.article, comment],
                 method: :delete,
                 data: { confirm: 'Are you sure?' }, :class => "btn btn-outline-danger btn-sm" %>
      </div>
    </div>
  <% end %>
  <hr class="my-4">
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <form>
    <div class="form-group">
      <p>
        <% full_name = current_user.first_name + " " + current_user.last_name %>
        <%= form.text_field :commenter, :class => "form-control", :value => full_name, :readonly => "readonly" %>
      </p>
      <p>
        <%= form.text_area :body, :class => "form-control", :placeholder => "Write your comment here", :rows => "5" %>
      </p>
      <p>
        <%= form.submit :Submit, :class => "btn btn-primary col-11" %>
      </p>
    </div>
  <% end %>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <div class="field form-group">
    <%= form.text_field :first_name, :class => "form-control", placeholder: "First Name", :required => true %>
  </div>
  <div class="field form-group">
    <%= form.text_field :last_name, :class => "form-control", placeholder: "Last Name", :required => true %>
  </div>
  <%= form_group_for form, :email, label: false  do %>
    <div class="field form-group">
      <%= form.email_field :email, :class => "form-control #{'border border-danger' if form.object.errors[:email].present? }", placeholder: "Email Address", :required => true %>
    </div>
  <% end %>
  <%= form_group_for form, :password, label: false  do %>
    <div class="field form-group">
      <%= form.password_field :password, :class => "form-control #{'border border-danger' if form.object.errors[:password].present? }", placeholder: "Password", :required => true %>
    </div>
  <% end %>
  <%= form_group_for form, :password_confirmation, label: false  do %>
    <div class="field form-group">
      <%= form.password_field :password_confirmation, :class => "form-control #{'border border-danger' if form.object.errors[:password_confirmation].present? }", placeholder: "Confirm Password", :required => true %>
    </div>
  <% end %>
  <%= form.submit :Submit, :class => "btn btn-primary btn-lg" %>
  <%= link_to 'Back', root_url, :class => "btn btn-dark btn-lg" %>
<% end %>

app/views/users/_role.html.erb
  <%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field form-group">
    <%= form.text_field :first_name, :class => "form-control", placeholder: "First Name" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :last_name, :class => "form-control", placeholder: "Last Name" %>
  </div>
  <div class="field form-group">
    <%= form.text_field :email, :class => "form-control", placeholder: "Email Address", :readonly => "readonly" %>
  </div>
  <% if @user.role == "admin" %>
    <div class="field form-group">
      <%= form.select :role, options_for_select([[User.roles, 'admin'], [User.roles, 'user']]), {}, {class: "form-control" , disabled: true} %>
    </div>
  <% else %>
    <div class="field form-group">
      <%= form.select :role, options_for_select([[User.roles, 'admin'], [User.roles, 'user']]), {}, {class: "form-control"} %>
    </div>
  <% end %>
  <%= form.submit :Submit, :class => "btn-mg-bottom btn btn-primary btn-block" %>
<% end %>

app/views/users/edit.html.erb
<%= render "sessions/destroy" %>
<div class= "login-box">
  <h1>Edit</h1>
  <%= render 'role', user: @user %>
  <%= link_to 'Back', users_url, :class => "btn btn-outline-dark btn-block" %>
</div>

app/views/users/index.html.erb
<h6 id="notice"><%= notice %></h6>
<%= render "sessions/destroy" %>
<div class="container border border-light bg-color">
  <h1>User's List</h1>
  <% @users.each_with_index do |user_element, index| %>
    <div>
      <hr class="my-4">
      <div class="row ">
        <div class="col-md-2">
          <p><%= index+1 %></p>
        </div>
        <div class="col-md-3">
          <% full_name = user_element.first_name + " " + user_element.last_name %>
          <p><%= full_name %></p>
        </div>
        <div class="col-md-3">
          <p><%= user_element.email %></p>
        </div>
        <div class="col-md-2">
          <p><%= user_element.role %></p>
        </div>
        <div class="col-md-2">
          <%= link_to ('<i class="btn-mg fas fa-user-edit"></i>').html_safe, edit_user_path(user_element) %>
          <% if user_element.role == "user" %>
            <%= link_to ('<i class="btn-mg far fa-trash-alt"></i>').html_safe, user_path(user_element),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="input-box">
    <%= link_to 'Back', root_url, :class => "btn btn-block btn-outline-dark" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container comments">
  <h1>Sign Up</h1>
  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="input-box">
  <h1 id="notice"><%= notice %></h1>
  <%= link_to 'Home', root_url, :class => "btn btn-outline-primary" %>
</div>

app/views/welcome/index.html.erb
<% if current_user %>
  <%= render "sessions/destroy" %>
  <div class="jumbotron input-box bg-color">
    <h1 class="display-4">Welcome To The BlogApp</h1>
    <p class="lead">Showcase your knowledge through your <strong>Blog</strong></p>
    <hr class="my-4">
    <%= link_to 'My Blog', articles_path, :class => "btn btn-primary" %>
    <% if (current_user.role == "admin") %>
      <%= link_to 'User Dashboard', users_path, :class => "btn btn-outline-primary" %>
    <% end %>
  </div>
<% else %>
  <%= render "sessions/login" %>
<% end %>